Start breakup

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,23 +1,24 @@
-#!/usr/bin/env bash
-sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
-sudo chsh -s /usr/bin/zsh
+#!/bin/bash
 
-echo "Updating the yadm repo origin URL"
-yadm remote set-url origin "dotfiles:ags131/dotfiles"
+# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
+# execute all executable files (excluding templates and editor backups) in the
+# ~/.config/yadm/bootstrap.d directory when run.
 
-cd "$HOME"
-echo "Init submodules"
-yadm submodule update --recursive --init
+set -eu
 
+# Directory to look for bootstrap executables in
+BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
 
-if ! grep 'Host dotfiles' ~/.ssh/config ; then
-  cat - << EOF >> ~/.ssh/config
-Host dotfiles
-  Hostname github.com
-  User git
-  IdentityFile ~/.ssh/dotfiles
-EOF
+if [[ ! -d "$BOOTSTRAP_D" ]]; then
+    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    exit 1
 fi
 
-echo "Decrypt files"
-yadm decrypt
+find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
+    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+        if ! "$bootstrap"; then
+            echo "Error: bootstrap '$bootstrap' failed" >&2
+            exit 1
+        fi
+    fi
+done
